[server]
# 服务器配置
headless = false
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = false

[browser]
# 浏览器配置
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[global]
# 全局配置
developmentMode = false
showWarningOnDirectExecution = false

[theme]
# 主题配置
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[runner]
# 运行器配置
magicEnabled = true